### ISSUE TITLE
How to adapt the code to download email attachment and update another ESP32? (ESF-121)

### ISSUE THREAD

**Issue by rtek1000** [espressif/esp-serial-flasher#101]
### Is your feature request related to a problem?

Hello, I would like to adapt this serial-flasher (UART) to work in conjunction with an email client.

The idea is that one ESP32 (ESP-programmer) is just the updater and it should download the binary file attached to the email and update another ESP32 (ESP-target). Without saving the attached file anywhere, and the example code already works like this. In case an error occurs during the update, it is still possible to try the update again.

In my case, the binary file to be updated is generated in the Arduino IDE, which is a single file (firmware.bin). So I must send other files in the email as well.

I found a reference to update 4 files in ESP32:
> /esp32/tools/partitions/boot_app0.bin at 0xe000
> /esp32/tools/sdk/bin/bootloader_qio_80m.bin at 0x1000
> sketch.ino.bin at 0x10000
> sketch_dec.ino.partitions.bin at 0x8000

So, I must remove the part related to accessing Flash via SPI, from esp-serial-flasher lib.

- What about MD5?
- - Does the ESP-programmer not need this check, since the file is not in the ESP programmer's Flash memory?

### Describe the solution you'd like

What I would like is for there to be an example available, with both libraries integrated (email attachment + serial flasher), but as I couldn't find it, I'll try to make it work, and avoid having to travel to another city to have to reprogram an ESP32 controlling a church tower clock (yes, an ESP32 is a lot for the clock, but I also want to implement Dwin Display update, which uses W25Q128 memory, instead of having to manually insert the update SD card, it will take time a little bit to finish this).

### Additional context

This example shows how to read Email and update firmware if firmware file name in attachments matches:
https://github.com/mobizt/ESP-Mail-Client/blob/5c6e231e181ff863a325bba38eb692e88c087abb/examples/IMAP/Firmware_Update_Attachment/Firmware_Update_Attachment.ino

How to Create .bin (binary) Files from Sketch on Arduino IDE:
https://randomnerdtutorials.com/bin-binary-files-sketch-arduino-ide/

Flashing ArduinoIDE .bin via Espressif ESP32 Flash Download Tool:
https://github.com/espressif/arduino-esp32/issues/3409

**Comment by dobairoland** [comment]
I'm sorry but we cannot provide an example for everything and this is out-of-scope for esp-serial-flasher which deals with how to flash a target MCU and not how to obtain the image for flashing.
