### ISSUE TITLE
esp-serial-flasher needs "/n"  (IDFGH-13612) (ESF-155)

### ISSUE THREAD

**Issue by seulater** [espressif/esp-serial-flasher#115]
### Answers checklist.

- [X] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [X] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [X] I have searched the issue tracker for a similar issue and not found a similar issue.

### General issue report

Using [esp-serial-flasher](https://github.com/espressif/esp-serial-flasher) I noticed that in example_common.c line 347:
printf("\rProgress: %d %%", progress);

It should be printf("\rProgress: %d %%\n", progress);

Otherwise it never prints the progress.

**Comment by DNedic** [comment]
Thank you for reporting this @seulater , this is actually not by accident, the carriage return at the start of the string will make sure that new lines for progress will be printed over old ones, resulting in a changing counter in a single line.

I can't reproduce any other behavior, can you provide more information on the setup which you encountered that behavior with?

**Comment by DNedic** [comment]
Could you provide info on which port you encountered this behavior with so we can try to reproduce it?

**Comment by DNedic** [comment]
I assume you're using the ESP port and the USB interface with the `esp32_usb_cdc_acm` example, or are you using an user port? Can you go into which OS and serial monitoring tool you are using, it might be an issue on the host side?
