### ISSUE TITLE
How to transmit 0xdb?

### ISSUE THREAD

**Issue by idfulin** [espressif/esp-serial-flasher#13]
_static const uint8_t BD_REPLACEMENT[2] = {0xdb, 0xdd};_  From this point of view, if the escape of 0xbd is _{0xdb, 0xdd}_, then how is the transmission of 0xdb?
There is a contradiction between _if (ch == 0xdd) { buff[i] = 0xbd;  }_ in _SLIP_receive_data_ API(line 55 to 77) and _if (data[i] != 0xc0 && data[i] != 0xdb) { to_write++; continue; }_, _else { RETURN_ON_ERROR( serial_write(BD_REPLACEMENT, 2) ); }_ in SLIP_send API(line 108 to 138).

**Comment by MaValki** [comment]
Hi idfulin,

Indeed there was bug in `SLIP_receive_data` function. I accidentally confused `0xdb` character with `0xbd`. 
Thank you for pointing this out. It has been fixed merged to master.
