### ISSUE TITLE
How to set SpiFlashConfig?

### ISSUE THREAD

**Issue by hehao9051** [espressif/esp-serial-flasher#18]
When i use esp_download tool, i need set spiflashconfig. But in this project, i can't find how to set it. 
![image](https://user-images.githubusercontent.com/10400564/106377614-39943780-63d9-11eb-9ac2-7d49d0cbd254.png)

**Comment by MaValki** [comment]
Hi,

FLASH  SIZE of attached flash chip is detected automatically, however, modifying SPI SPEED and SPI MODE is unimplemented. Those parameters are included at the beginning of generated binary and can be selected in menuconfig (_serial flash config_ submenu). Do you have to override it while flashing for some reason ?

Hope this helps.

**Comment by hehao9051** [comment]
@MaValki  Thanks we don't need that. Because we alaway use the tools, so i mistakenly think the config have to set it by flasher.
