### ISSUE TITLE
[8266 stub loader]FLASH_DATA Command return C1(checksum error) 

### ISSUE THREAD

**Issue by songjiaxiu-espressif** [espressif/esp-serial-flasher#2]
Hi, 
I have been in trouble recently and hope to get your help.
situation:
when ubuntu PC  recv:`4f 48 41 49`  means  the stub loader running!
next,  send `FLASH_*`  command liles demo to ESP8266 stubloader, it returns error c1(checksum error) , I doubt the correctness of stub load's checksum，Looking forward to your reply. thx

**Comment by MaValki** [comment]
Hi songjiaxiu,
I do not quite understand what you are trying to achieve. Could you please clarify that ?
Note that esp-serial-flasher does not support ESP8266 yet. Currently only ESP32 is supported.
