### ISSUE TITLE
No error while flashing but no behaviour modification  (ESF-17)

### ISSUE THREAD

**Issue by MarcoOlmi** [espressif/esp-serial-flasher#29]
I'm trying to reprogram an ESP32-WROOM-32E using my mircohip PIC32MZ that read files from SD card.
My target is to have AT Commands on UART0. the software work well if programmed with PC on an AZDelivery board with ESP32-WROOM-32.
It seems everything work well (no error while programming) but when i restart my board, ESP32-WROOM-32E doesn't notify "ready" on UART0.

can you help me to find my mistake?

**Comment by MaValki** [comment]
Hi, I'll try my best. 

Since there is no official port for PIC, I assume you wrote your own.

Does WROOM module print anything at all after programming?
How big is AT command binary and what starting address do you use?

**Comment by MarcoOlmi** [comment]
Yes a wrote my one. And I hope I will be able to share it.

Actually my "map" is the same i've seen from python command on PC.

0x00001000 /*bootloader/bootloader.bin */
0x00008000 /*partition_table/partition-table.bin */
0x0000F000  /*phy_init_data.bin */
0x00010000  /*ota_data_initial.bin */
0x00020000  /*at_customize.bin */
0x00021000  /*customized_partitions/ble_data.bin */
0x00024000  /*customized_partitions/server_cert.bin */
0x00026000  /*customized_partitions/server_key.bin */
0x00028000  /*customized_partitions/server_ca.bin */
0x0002a000  /*customized_partitions/client_cert.bin */
0x0002c000  /*customized_partitions/client_key.bin */
0x0002e000  /*customized_partitions/client_ca.bin */
0x00030000  /*customized_partitions/factory_param.bin */
0x00037000  /*customized_partitions/mqtt_cert.bin */
0x00039000  /*customized_partitions/mqtt_key.bin */
0x0003b000  /*customized_partitions/mqtt_ca.bin */
0x00100000  /*asp-at.bin */

esp-at.bin file is 1.304.464 byte

no messages after programming

I have enabled also the MD5 check. Only a check error on ble_data.bin  (could this be the problem on everithing?)
The only diffrence from the original software is the reset after programming. I have no PIC32 line connected to ESP32 RST so... i simply turn off my board.

**Comment by MaValki** [comment]
Interesting... I would assume at least some error message from ROM bootloader, even if it wasn't able to boot due to flash integrity for example (wrong MD5 chucksum). 
You can try `esp_loader_flash_finish(true)` in order to reboot without reset.
Does MD5 check consistently fail on ble_data.bin? Not sure, whether this can cause the issue. To find out, you can try to remove it temporarily (from both partition table, and flashing).

**Comment by MarcoOlmi** [comment]
MD5 check consistently fail on ble_data.bin! Even if I reprogram only the ble_data.bin file.

Restarting in normal (NO UPDATE) mode I receive the following messages.
As you can see, and one point it restart to boot. Something like an error while loading. 
 
ets Jul 29 2 019 12:21:46
rst:0x1 (POW ERON_RESET),boot :0x13 (SPI_FAST_ FLASH_BOOT)
configsip: 0 , SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:7252
load:0x6f727265,len:1528504690
1150 mmu set 00010000, pos 00010000
1150 mmu set 00020000, pos 00020000
1150 mmu set 00030000, pos 00030000
1150 mmu set 00040000, pos 00040000
1150 mmu set 00050000, pos 00050000
1150 mmu set 00060000, pos 00060000
1150 mmu set 00070000, pos 00070000
1150 mmu set 00080000, pos 00080000
1150 mmu set 00090000, pos 00090000
1150 mmu set 000a0000, pos 000a0000
Does MD5 check consistently fail on ble_data.bin? 1150 mmu set 000b0ets Jul 29  2019 12:21:46
rst:0x10 (RT CWDT_RTC_RESET), boot:0x13 (SPI_F AST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:7252
load:0x6f727265,len:1528504690

**Comment by MarcoOlmi** [comment]
The same happens also if bluetooth is not selected in menuconfig builded

**Comment by MaValki** [comment]
At this point I am not able to figure out, why it does not work.
Perhaps, we may start with much simpler example,  such as `hello-world`.
Flashing bootloader, partition table and application first with `esptool` as you did before. Then re-flash just application and check if you can see the output in terminal.
