### ISSUE TITLE
Zephyr port  (ESF-14)

### ISSUE THREAD

**Issue by beriberikix** [espressif/esp-serial-flasher#34]
Has anyone looked into porting this to [Zephyr](https://www.zephyrproject.org/)? Practically speaking that would allow a much broader range of devices (and for some solving the need for #28.)

**Comment by kaartee** [comment]
Heads up: we have issued PR #50.

**Comment by dobairoland** [comment]
Closed by 3982a207a30f75493dbc0b334d525081d6a89806
