### ISSUE TITLE
ESP32 secure bootloader

### ISSUE THREAD

**Issue by huybk213** [espressif/esp-serial-flasher#38]
Hi everyone,

Does esp-serial-flasher support flash secure bootloader key and efuse?

Thanks.

**Comment by MaValki** [comment]
Hi,

Unfortunately, these features are unsupported. `esp-serial-flasher` is supposed to be simple C implementation of `esptool`, thus it's not intended for efuse configuration.

**Comment by huybk213** [comment]
Thanks @MaValki
