### ISSUE TITLE
Serial Flasher without UART0  (ESF-15)

### ISSUE THREAD

**Issue by rajmasud** [espressif/esp-serial-flasher#43]
I was wondering if it is possible to flash the firmware to the ESP32 using a different UART/SPI other than UART0. Thank you.

**Comment by MaValki** [comment]
I'm afraid not. Only UART0 is dedicated for programming.

**Comment by igrr** [comment]
Flashing over SPI (for the ESP chips which support this) is now in plan, we will update this issue once there is progress.
