### ISSUE TITLE
Is this Lib support to FreeRTOS (ESF-4)

### ISSUE THREAD

**Issue by phanminhtien** [espressif/esp-serial-flasher#47]
Is this Lib support to FreeRTOS ? 
When I use 2 tasks FreeRTOS. I can not use this Lib, but if only using main(), it works. Thanks a lot

**Comment by dobairoland** [comment]
Here is an example which is for ESP-IDF (FreeRTOS based): https://github.com/espressif/esp-serial-flasher/tree/master/examples/esp32_example

A complex external example using esp-serial-flasher can be found here: https://github.com/espressif/esp-usb-bridge
