### ISSUE TITLE
DEBUG: Error: COMMAND_FAILED    [E][FLASHER.ino:60] flash_bin(): Flash start operation failed.

### ISSUE THREAD

**Issue by Hoel** [espressif/esp-serial-flasher#5]
I ran the project as is in the arduino ecosystem which has the lastest ESP32 core (updated yesterday), and while it connects successfully to the target it fails to even start flashing.

The wiring has been double checked and is conform to the defined ports, which is confirmed by the fact it does connect correctly.
I added debug statements in loader_port_serial_write and loader_port_serial_read just to see what was sent and received, some datas are exchanged.

Is this example even functional?
It shouldnt change anything that it runs in arduino ecosystem since the underlaying SDK is the same, in the arduino setup function i only call app_main(); and nothing else.
The project is attached below.
[FLASHER.zip](https://github.com/espressif/esp-serial-flasher/files/4767724/FLASHER.zip)

```
[I][FLASHER.ino:45] flash_bin(): Connected to target
DEBUG: Error: COMMAND_FAILED
[E][FLASHER.ino:63] flash_bin(): Flash start operation failed.
```

**Comment by Hoel** [comment]
UPDATE :
After more testing i found the source of the problem (but not how to solve it).
Apparently the reson for the error is the offset. 
In my case i need to flash a binary of length 0x3000 at offset 0x3FD000.
If i set the offset to 0x10000 everything works fine.
If i set the offset to 0x3FD000 then i get **Flash start operation failed**.
So for some reason the function **esp_loader_flash_start** cannot handle another offset than 0x10000 or at least not it cannot handle 0x3FD000.
Please let me know how i could fix this issue because i really have to flash at 0x3FD000, flashing at 0x10000 is not an option here.

**Comment by Hoel** [comment]
UPDATE : 
So i found the problem, it was related to the ROM which assume the flash to be 2MB, and so anything after this limit is considered invalid.
I found the PR from someone else adressing this issue by adding a command to set flash parameters before **esp_loader_flash_start** https://github.com/espressif/esp-serial-flasher/pull/3/files
which fixed the problem.

**Comment by MaValki** [comment]
Hi Hoel,
Thank you for contributing with detailed description of this issue. As you mentioned above, it has already been reported, and I have implemented functionality that queries flash size and adjusts it in ROM accordingly. I expect those changes to be merged into master in one week.
