### ISSUE TITLE
esp-serial-flasher md5 problem (ESF-23)

### ISSUE THREAD

**Issue by JeffreyEWright** [espressif/esp-serial-flasher#52]
Nevermind...vie dumm von mir...vie dumm.  I found the problem. My uart driver was configured for SW flow control...and what is the XOFF character?...yes, 0x13 ...the md5 command...vie dumm

Hello;
I've implemented the example on my client's STM32L431, and I can successfully flash the bootloader, partition table, and application via UART0.  However, IF I include the MD5 checksum, **_it stops responding after I flash the bootloader partition_**??
The response after send_cmd_md5() is odd, since command is returned as 0x24, but should be 0x13. Nevertheless, the correct MD5 checksum appears to be returned correctly, BUT it is **_shifted by one byte_**, with the first byte being written at "response.common.value"...is the 0x24 command valid?...If so, I cannot find any documentation to explain its meaning?

SO, any help would be greatly appreciated!

c0 01 _**24**_ 00 20 40 16 00 37 33 65 38 38 62 35 63 33 37 65 63 39 30 36 30 64 66 35 33 30 39 65 63 39 31 38 34 65 34 33 64 00 00 00 00 c0
For reference:

typedef struct __attribute__((packed))
{
    uint8_t direction;
    uint8_t command;    // One of command_t
    uint16_t size;
    uint32_t value;
} common_response_t;

typedef struct __attribute__((packed))
{
    common_response_t common;
    uint8_t md5[MD5_SIZE];     // ROM only
    response_status_t status;
} rom_md5_response_t;

Thanks.

**Comment by dobairoland** [comment]
Based on the edited comment, this was solved.
