### ISSUE TITLE
Progress-Bar ?  (ESF-34)

### ISSUE THREAD

**Issue by franz-ms-muc** [espressif/esp-serial-flasher#60]
Hi, 
possible to have a Progress Bar ? 

not only a 
```
Start programming
Progress: 100 %
```

but more like: 
```
Start programming
Progress: 40 %
Progress: 60 %
Progress: 80 %
Progress: 100 %
```

**Comment by DNedic** [comment]
Hello @franz-ms-muc , thank you for the feature request. At the moment this is only in example code and as you can see [here](https://github.com/espressif/esp-serial-flasher/blob/f8b949d9e040b25e13bd67d095af7e2d018993d4/examples/common/example_common.c#LL245C13-L245C21) it does print out the progress every time a chunk of 1024 bytes is written, often the size of the partition is lower than that and that is when you see
```
Start programming
Progress: 100 %
```

We could reduce the size of the buffer but that would just reduce the efficiency and speed of flashing for no real gain. With larger example binaries this would print out more granular progress. 

As this is example code you are free to modify it when using it as a reference.
