### ISSUE TITLE
Add support for flashing through native USB (ESF-43)

### ISSUE THREAD

**Issue by seulater** [espressif/esp-serial-flasher#64]
Would like to see an addition where an ESP32-S3 could flash another ESP32-S3 via USB to one another.

**Comment by dobairoland** [comment]
Can you please clarify your request? To the best of my knowledge ESP32-S3 is already supported both as a target and host.

**Comment by dobairoland** [comment]
Ok, I see. Thanks for the clarification. I rename the task, I hope you don't mind.

**Comment by esp32testing** [comment]
Can you make an example code for build a flasher to flash the ESP32 via usb using a raspberry pi ?
