### ISSUE TITLE
Error when executing example (ESF-45)

### ISSUE THREAD

**Issue by pepopi1** [espressif/esp-serial-flasher#66]
Hello, when running the ESP32_example I get the error cannot connect to target. Error:2, how can I fix this? Thank you

**Comment by DNedic** [comment]
Hello, can you please provide more information on your setup and full `monitor` output. For instance, the wiring and the chips used.

**Comment by dobairoland** [comment]
I assume based on https://esp32.com/viewtopic.php?f=13&t=33657 that this can be closed.
