### ISSUE TITLE
Code can't be compiled with g++ 13.2.1 & -Wpedantic (ESF-71)

### ISSUE THREAD

**Issue by nazaryev-cool** [espressif/esp-serial-flasher#71]
### Port

-

### Target chip

-

### Hardware Configuration

-

### Log output

```plain
-
```

### More Information

For now it's only one warning that prevents us to build code with -Wpedantic:

```
../esp-serial-flasher/include/esp_loader.h:96:12: error: ISO C++ prohibits anonymous structs [-Werror=pedantic]
   96 |     struct {
      |            ^
cc1plus: all warnings being treated as errors
```

**Comment by DNedic** [comment]
Hello @nazaryev-cool , thank you for your submission, a solution is in the works.
