### ISSUE TITLE
`esp_loader_connect` fails in `detect_chip`

### ISSUE THREAD

**Issue by campbell-seer** [espressif/esp-serial-flasher#9]
I'm currently integrating this library into one of our boards and have noticed that the ESP32 sends 8 packets in response to `loader_sync_cmd()`. This causes `detect_chip` to fail because it expects a response to its register read, but actually processes one of the duplicated packets.

I receive this data:

```
[c0][01][08][04][00][07][07][12][20][00][00][00][00][c0]
[c0][01][08][04][00][07][07][12][20][00][00][00][00][c0]
[c0][01][08][04][00][07][07][12][20][00][00][00][00][c0]
[c0][01][08][04][00][07][07][12][20][00][00][00][00][c0]
[c0][01][08][04][00][07][07][12][20][00][00][00][00][c0]
[c0][01][08][04][00][07][07][12][20][00][00][00][00][c0]
[c0][01][08][04][00][07][07][12][20][00][00][00][00][c0]
[c0][01][08][04][00][07][07][12][20][00][00][00][00][c0]
```

`esptool` reads these 7 additional responses, see https://github.com/espressif/esptool/blob/master/esptool.py#L432 . Can we rely on always receiving 8 packets to a sync query? If so it's an easy fix, but not sure if different chips will have different behaviour. I'm a bit surprised that the code works for other devices at the moment, so let me know if I'm missing something :)

**Comment by campbell-seer** [comment]
Read over the code a bit more and see that `check_response` handles this by ignoring commands that aren't expected. So the issue must be that my rx buffer is overflowing, and then the packets are no longer aligned and so this check doesn't work. Sorry for the bad report :+1:

**Comment by MaValki** [comment]
Hi campbell-seer,
that is right, unwanted packets are ignored. `check_response` function only return in case of TIMEOUT or some other error.
If you have any additional questions, don't hesitate to ask.
