### ISSUE TITLE
Store Image to be flashed on host ESP32 SPIFFS and then flash from SPIFFS (ESF-113)

### ISSUE THREAD

**Issue by bilalmalik76** [espressif/esp-serial-flasher#96]
Is it possible to store the image to be flashed on host ESP32 SPIFFS and then flash it to target from SPIFFS?

**Comment by DNedic** [comment]
Hello @bilalmalik76 yes it is possible, `esp-serial-flasher` does not care where you get your binary from. You could even receive it continously in some way (as long as you know the total sizes), as we are doing in [esp-usb-bridge](https://github.com/espressif/esp-usb-bridge/blob/master/main/msc.c).
